MainPage = action_wheel:newPage()
action_wheel:setPage(MainPage)

events.TICK:register(function ()
    if action_wheel:getCurrentPage() ~= MainPage and not action_wheel:isEnabled()
      then action_wheel:setPage(MainPage) end
end)




CMYKPage = action_wheel:newPage()
MainPage:newAction(2)
    :title("Ink Arcana"):item("spectrum:pigment_palette")
    :onLeftClick(function() action_wheel:setPage(CMYKPage) end)

TopazPage = action_wheel:newPage()
AmethystPage = action_wheel:newPage()
CitrinePage = action_wheel:newPage()
OnyxPage = action_wheel:newPage()

CMYKPage:newAction()
    :title("MATTER"):item("spectrum:topaz_shard")
    :setHoverColor(vectors.hexToRGB("0FF"))
    :onLeftClick(function() action_wheel:setPage(TopazPage) end)
CMYKPage:newAction()
    :title("ENERGY"):item("spectrum:citrine_shard")
    :setHoverColor(vectors.hexToRGB("FF0"))
    :onLeftClick(function() action_wheel:setPage(CitrinePage) end)
CMYKPage:newAction()
    :title("TIME"):item("minecraft:amethyst_shard")
    :setHoverColor(vectors.hexToRGB("F0F"))
    :onLeftClick(function() action_wheel:setPage(AmethystPage) end)
--uncomment this when the TIME IS RIGHT 
CMYKPage:newAction()
    :title("VOID"):item("spectrum:onyx_shard")
    :setHoverColor(vectors.hexToRGB("000"))
    :onLeftClick(function() action_wheel:setPage(OnyxPage) end)





CyanPage = action_wheel:newPage()
LightBluePage = action_wheel:newPage()
BluePage = action_wheel:newPage()
LimePage = action_wheel:newPage()

TopazPage:newAction()
    :title("Cyan"):item("minecraft:cyan_dye")
    :setHoverColor(vectors.hexToRGB("169c9c"))
    :onLeftClick(function() action_wheel:setPage(CyanPage) end)
TopazPage:newAction()
    :title("Light Blue"):item("minecraft:light_blue_dye")
    :setHoverColor(vectors.hexToRGB("3ab3da"))
    :onLeftClick(function() action_wheel:setPage(LightBluePage) end)
TopazPage:newAction()
    :title("Blue"):item("minecraft:blue_dye")
    :setHoverColor(vectors.hexToRGB("3c44aa"))
    :onLeftClick(function() action_wheel:setPage(BluePage) end)
TopazPage:newAction()
    :title("Lime"):item("minecraft:lime_dye")
    :setHoverColor(vectors.hexToRGB("80c71f"))
    :onLeftClick(function() action_wheel:setPage(LimePage) end)


MagentaPage = action_wheel:newPage()
PinkPage = action_wheel:newPage()
PurplePage = action_wheel:newPage()
RedPage = action_wheel:newPage()

AmethystPage:newAction()
    :title("Magenta"):item("minecraft:magenta_dye")
    :setHoverColor(vectors.hexToRGB("c74ebd"))
    :onLeftClick(function() action_wheel:setPage(MagentaPage) end)
AmethystPage:newAction()
    :title("Pink"):item("minecraft:pink_dye")
    :setHoverColor(vectors.hexToRGB("r38baa"))
    :onLeftClick(function() action_wheel:setPage(PinkPage) end)
AmethystPage:newAction()
    :title("Purple"):item("minecraft:purple_dye")
    :setHoverColor(vectors.hexToRGB("8932b8"))
    :onLeftClick(function() action_wheel:setPage(PurplePage) end)
AmethystPage:newAction()
    :title("Red"):item("minecraft:red_dye")
    :setHoverColor(vectors.hexToRGB("b02e26"))
    :onLeftClick(function() action_wheel:setPage(RedPage) end)


YellowPage = action_wheel:newPage()
BrownPage = action_wheel:newPage()
GreenPage = action_wheel:newPage()
OrangePage = action_wheel:newPage()

CitrinePage:newAction()
    :title("Yellow"):item("minecraft:yellow_dye")
    :setHoverColor(vectors.hexToRGB("fed83d"))
    :onLeftClick(function() action_wheel:setPage(YellowPage) end)
CitrinePage:newAction()
    :title("Brown"):item("minecraft:brown_dye")
    :setHoverColor(vectors.hexToRGB("835432"))
    :onLeftClick(function() action_wheel:setPage(BrownPage) end)
CitrinePage:newAction()
    :title("Green"):item("minecraft:green_dye")
    :setHoverColor(vectors.hexToRGB("5e7c16"))
    :onLeftClick(function() action_wheel:setPage(GreenPage) end)
CitrinePage:newAction()
    :title("Orange"):item("minecraft:orange_dye")
    :setHoverColor(vectors.hexToRGB("f9801d"))
    :onLeftClick(function() action_wheel:setPage(OrangePage) end)


BlackPage = action_wheel:newPage()
GrayPage = action_wheel:newPage()
LightGrayPage = action_wheel:newPage()
WhitePage = action_wheel:newPage()

OnyxPage:newAction()
    :title("Black"):item("minecraft:black_dye")
    :setHoverColor(vectors.hexToRGB("1d1d21"))
    :onLeftClick(function() action_wheel:setPage(BlackPage) end)
OnyxPage:newAction()
    :title("Gray"):item("minecraft:gray_dye")
    :setHoverColor(vectors.hexToRGB("474f52"))
    :onLeftClick(function() action_wheel:setPage(GrayPage) end)
OnyxPage:newAction()
    :title("Light Gray"):item("minecraft:light_gray_dye")
    :setHoverColor(vectors.hexToRGB("9d9d97"))
    :onLeftClick(function() action_wheel:setPage(LightGrayPage) end)
OnyxPage:newAction()
    :title("White"):item("minecraft:white_dye")
    :setHoverColor(vectors.hexToRGB("f9fffe"))
    :onLeftClick(function() action_wheel:setPage(WhitePage) end)